name: Apply Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform-validate:
    uses: ./.github/workflows/validate.yml
  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-validate
    steps:
      - uses: actions/checkout@v2
      - name: Terraform Apply
        uses: dflook/terraform-apply@v1.46.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
