name: Apply Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform-validate:
    uses: ./.github/workflows/validate.yml
  terraform-apply:
    runs-on: ubuntu-latest
    needs: terraform-validate
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/checkout@v2
      - name: Terraform Apply
        uses: dflook/terraform-apply@61432ffb5b94226bdfc9cd68a1702a2c40e0db8b
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

          name: Increment Version

      - name: Set name
        run: git config user.name "Gearbox Bot"

      - name: Set email
        run: git config user.email "gearbox@decaturrobotics.org"

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GIT_PUSH_TOKEN }}
          branch: ${{ github.head_ref }}
