name: Plan Terraform

on:
  pull_request:
    branches:
      - main

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Terraform Plan
      uses: dflook/terraform-plan@v1.46.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        