name: Validate Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: terraform-validate
      uses: dflook/terraform-validate@v1.46.1