name: Validate Terraform

on:
  workflow_call:
  pull_request:
    branches:
      - main

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    name: "Terraform Validate"
    steps:
      - uses: actions/checkout@v2
      - name: terraform-validate
        uses: dflook/terraform-validate@5e22e449923d40905db0b3ca67ebc5787e8b2dee
